### ISSUE TITLE
document element.hasAttribute behaviour or perhaps fix something...

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#1026]
Again I'm not sure if this is an issue with incrementalDom or Skate. Learning from problems with getAttribute being "null" I switched to using hasAttribute.

```
    static get props() {
        return {
            blockId: prop.string({ attribute: true }),
            actionStarted: prop.string({ attribute: true }),
            actionTaken: prop.string({ attribute: true }),
            hidden: prop.boolean({ attribute: true }),
        };
    }
```

When I check `element.hasAttribute("action-started")` it is true as the attribute value is a blank string. This `<conversation-response>` is rendered with Skate.

```
    renderCallback() {
        let blocks = [];
        this.store.getState().forEach(block => {
            blocks.push(<conversation-block id={block.templateId}></conversation-block>);
            if (block.hiddenResponse) {
                blocks.push(<conversation-response block-id={block.templateId} hidden></conversation-response>);
            } else {
                blocks.push(<conversation-response block-id={block.templateId}></conversation-response>);
            }
        });
        return blocks;
    }
```

I don't have any code that sets the attribute outside the function that checks with `hasAttribute` so I assume that the props are set to blank string during construction. If that is the case I think it is reducing the expressiveness. I think attributes should start out as not defined if their property has no default/initial value. Alternately the documentation should be very clear on this.

**Comment by treshugart** [comment]
When the spec churned and renamed `createdCallback()` to `constructor()`, they put more restrictions on custom elements saying you can't `setAttribute()` etc within the constructor. Thus, you have to do it on connected. Reflection logic got very tricky at this point. This changed awhile back and is something we want to address try and make simpler, possibly by making one-way attribute reflection (attribute updates the property, but not vice-versa) the default behaviour.

The `attribute` option is documented [here](https://skatejs.gitbooks.io/skatejs/content/docs/api/Component.html#renderedcallback---supersedes-static-rendered). If you don't want the attribute to be sync'd with the property when the property is set, but want the property to be set when the attribute is set, then you can do `{ attribute: { source: true }`.

Where is your `hasAttribute()` call? I don't see it in `renderCallback()` there. I feel like there is possibly a better way to do things here. I can hep recommend something if you can provide context for your `hasAttribute()` call.

**Comment by thepian** [comment]
The `hasAttribute` is in an onclick handler.

When you click an action element within the custom element the state of the custom element is updated. I controlled state with attributes "action-taken" and "action-started", but now I do it by checking and assigning the props, which in turn updates the attributes, that works. However the other way around seems to have problematic blank semantics.

**Comment by treshugart** [comment]
I'm not sure how to resolve this issue. Is your problem fixed? If you have an updated code example, or a webpackbin / jsbin / etc that I can look at, I'm happy to help further.

**Comment by thepian** [comment]
I tried to add some tests to cover this but I can't seem to run the /build

Are these the correct first time run commands?

```
npm install
node_modules/skatejs-build/bin/sk-bundle
node_modules/skatejs-build/bin/sk-tests
```

Running with node 7 I get the following errors:

```
fg-mac-pro:skatejs admin$ node_modules/skatejs-build/bin/sk-bundle
resolve failed:  { Error: Cannot find module 'skatejs-build'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/Shared/Projects/skatejs/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } skatejs-build
node_modules/nan
resolve failed:  { Error: Cannot find module '@webcomponents'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/Shared/Projects/skatejs/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions..js (/Users/Shared/Projects/skatejs/node_modules/rollup/bin/rollup:763:6)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/skatejs-build/rollup.config.js:9:22)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions..js (/Users/Shared/Projects/skatejs/node_modules/rollup/bin/rollup:763:6)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' } @webcomponents

  error: unknown option `--config'

resolve failed:  { Error: Cannot find module 'skatejs-build'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/Shared/Projects/skatejs/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } skatejs-build
node_modules/nan
resolve failed:  { Error: Cannot find module '@webcomponents'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/Shared/Projects/skatejs/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/Shared/Projects/skatejs/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions..js (/Users/Shared/Projects/skatejs/node_modules/rollup/bin/rollup:763:6)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Shared/Projects/skatejs/node_modules/skatejs-build/rollup.config.js:9:22)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions..js (/Users/Shared/Projects/skatejs/node_modules/rollup/bin/rollup:763:6)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' } @webcomponents

  error: unknown option `--config'

Hash: 5aa5a6bb26f4093a0fa1
Version: webpack 1.13.3
Time: 4892ms
                          Asset     Size  Chunks             Chunk Names
        dist/index-with-deps.js   108 kB    0, 1  [emitted]  dist/index-with-deps.js
    dist/index-with-deps.min.js  31.9 kB    1, 0  [emitted]  dist/index-with-deps.min.js
    dist/index-with-deps.js.map   127 kB    0, 1  [emitted]  dist/index-with-deps.js
dist/index-with-deps.min.js.map   246 kB    1, 0  [emitted]  dist/index-with-deps.min.js
    + 37 hidden modules

WARNING in dist/index-with-deps.min.js from UglifyJs
Side effects in initialization of unused variable array [./src/api/prop.js:12,13]
Side effects in initialization of unused variable boolean [./src/api/prop.js:19,13]
Side effects in initialization of unused variable number [./src/api/prop.js:32,13]
Side effects in initialization of unused variable string [./src/api/prop.js:39,13]
Side effects in initialization of unused variable isFunction [./src/util/is-type.js:1,13]
Side effects in initialization of unused variable isObject [./src/util/is-type.js:2,13]
```

**Comment by treshugart** [comment]
@thepian check the https://github.com/skatejs/skatejs/blob/master/CONTRIBUTING.md file. I've updated it for the latest commands. I made a move to Webpack 2 for this repo, but not `skatejs-build` so had to switch to NPM scripts.

**Comment by thepian** [comment]
Wrote two tests that I think shows the issue. It seems clear to me that there is a bad conversion somewhere.

https://github.com/thepian/skatejs/commit/4d68318cfb004a33aea6ff02248f5be0f36547a3
