### ISSUE TITLE
Issue with SSR example

### ISSUE THREAD

**Issue by priand** [skatejs/skatejs#1505]
## Bug report
* Skate version: 5.2.3 (`npm info skatejs version`)
* Affected browsers (and versions): n/a

### Current behaviour
`npm start` on the SSR example (skatejs/packages/ssr/example) generates an error with undom. Looks like undom/register does not exists in undom 0.3.3

> ssr-wc@1.0.0 start /Users/priand/CommerceCloudDev/source/StencilJS/skatejs/packages/ssr/example
> node .

module.js:549
    throw err;
    ^

Error: Cannot find module 'undom/register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/priand/CommerceCloudDev/source/StencilJS/skatejs/packages/ssr/register/index.js:14:1)
    at Module._compile (module.js:652:30)
    at loader (/Users/priand/CommerceCloudDev/source/StencilJS/skatejs/packages/ssr/example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/priand/CommerceCloudDev/source/StencilJS/skatejs/packages/ssr/example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssr-wc@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ssr-wc@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Expected behaviour

Should run :-)

**Comment by treshugart** [comment]
Hmm, interesting. I'm looking at Undom 0.3.3 here and it looks like it's there.

<img width="374" alt="screen shot 2018-08-30 at 12 05 00 am" src="https://user-images.githubusercontent.com/136556/44792946-6a5c5b00-abe8-11e8-9243-643fa3efa933.png">

Did you ensure you ran `bolt` after cloning the repo? You also have to `npm i` in the examples directory.

**Comment by priand** [comment]
Yeah, it the module is there but there is no 'register' function.
I initially did not run bolt as I did not know that the example required it. I now did it but got a different error, see bellow ;-(

I'd like to start from scratch using a fresh clone. What commands need to be run in order to make the ssr example run?

> ssr-wc@1.0.0 start /Users/priand/webcomponents/skatejs/packages/ssr/example
> node .

/Users/priand/webcomponents/skatejs/packages/ssr/example/index.js:13
server.connection({
       ^

TypeError: server.connection is not a function
    at Object.<anonymous> (/Users/priand/webcomponents/skatejs/packages/ssr/example/index.js:13:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
