### ISSUE TITLE
Creating component instance using `new` while skatejs-web-components is on the page throws in Chrome 55

### ISSUE THREAD

**Issue by bengummer** [skatejs/skatejs#841]
When trying to create a new component instance using `const testInstance = new TestComponent();` works fine in Chrome 53 (stable) and Chrome 55 (canary).

However when the https://github.com/skatejs/web-components polyfills are on the page, Chrome 55 throws:

```console
Uncaught TypeError: Illegal constructor (document-register-element.node.js?a0fe:1353)
    at HTMLElement.e.(anonymous function) (https://unpkg.com/skatejs-web-components@1.2.1/dist/index-with-deps.min.js:24:2713)
    at Ctor.Component (https://unpkg.com/skatejs@2.0.0/dist/index-with-deps.js:1968:42)
    at new Ctor (https://unpkg.com/skatejs@2.0.0/dist/index-with-deps.js:1991:96)
    at HTMLButtonElement.document.getElementById.addEventListener (file:///Users/bgummer/Documents/followup/index.html:22:24)
```

* Example with `skatejs-web-components` polyfills (fails on Canary): [with-skate-wc-polyfills.html](https://rawgit.com/bengummer/081b007c16c9df123efd34fbefe9dfaa/raw/03916922fcb926441a2aea7c9eff2816a8705456/with-skate-wc-polyfills.html)
* Example with `skatejs-web-components` polyfills (works as expected on Canary): [without-skate-wc-polyfills.html](https://rawgit.com/bengummer/081b007c16c9df123efd34fbefe9dfaa/raw/03916922fcb926441a2aea7c9eff2816a8705456/without-skate-wc-polyfills.html)

**Comment by bengummer** [comment]
possible fix on https://github.com/skatejs/skatejs/tree/841-new-ctor-fix-chrome-55
