### ISSUE TITLE
Get working in JSDOM

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#884]
JSDOM seems to be a fairly common environment to run tests in, and also for server-side rendering. It'd be good to try and get it working so we can cover these use-cases.

**Comment by treshugart** [comment]
Implementing in https://github.com/skatejs/build/issues/424

**Comment by treshugart** [comment]
JSDOM doesn't have Mutation Events (removed in 8.5: https://github.com/tmpvar/jsdom/issues/1030#issuecomment-235187496) and Mutation Observers (been in dev for ages: https://github.com/tmpvar/jsdom/issues/639). I'm not sure it's a good idea to lock ourselves to an older version while having to hack in a `DOMParser` for `skatejs-named-slots` to run.

If I try hacking in a `DOMParser` like:

```js
global.DOMParser = require('jsdom').jsdom().defaultView.DOMParser;
```

I get the error:

```sh
ERROR in ./~/har-validator/lib/schemas/timings.json
Module parse failed: /Users/tshugart/Sites/skatejs/skatejs/node_modules/har-validator/lib/schemas/timings.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:12)
    at Parser.pp$4.raise (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/tshugart/Sites/skatejs/skatejs/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/tshugart/Sites/skatejs/skatejs/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/tshugart/Sites/skatejs/skatejs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/har-validator/lib/schemas/index.js 18:11-36
```

**Comment by treshugart** [comment]
Closing until JSDOM implements this.
